dunning_cruncher/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from core import views

admin.autodiscover()


urlpatterns = patterns('',
                       url(r'^$', views.index),
                       url(r'^login/?$', views.login),
                       url(r'^main/$', views.tracker),
                       url(r'^logout/?$', views.logout_view),
                       url(r'^reporting/(?P<ryear>\d{4})/(?P<rmonth>\d+)/$', views.reporting),
                       url(r'^ajax/$', views.ajax),
                       url(r'^overview/$', views.edit),
                       url(r'^pdf_get/(?P<file_name>.+)/$', views.serve_pdf),
                       url(r'^pdfgen/$', views.pdfgeneration),
                       url(r'^sreport/([A-Z]{1,2})/(\d{4})/(\d{1,2})/(\d{1,2})', views.csv_report),
                       url(r'^password_change/$',
                           auth_views.password_change,
                           {'template_name': 'password_change_form.html'},
                           name='password_change'),
                       url(r'^password_change_done/$',
                           auth_views.password_change_done,
                           {'template_name': 'password_change_done.html'},
                           name='password_change_done'),
                       url(r'^(?P<drafttype>[a-z]{4})/(?P<dnumber>\d+)/(?P<language>[A-Z]{2})/$', views.draft),
                       url(r'^reminders/(?P<year>\d{4})/(?P<week>\d+)/$', views.tracking_calendar),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^password_reset/$', auth_views.password_reset,
                           {'from_email': 'admin@dunnings.com'},
                           name="password_reset"),
                       url(r'^password_reset_done/$', auth_views.password_reset_done,
                           name="password_reset_done"),
                       url(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)\/(?P<token>.+)/$', auth_views.password_reset_confirm,
                           name="password_reset_confirm"),
                       url(r'^password_reset_complete/$', auth_views.password_reset_complete,
                           name="password_reset_complete"),
)

core/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django import forms
from django.forms import ModelForm


class Vendor(models.Model):
    vname = models.CharField(max_length=200)
    vnumber = models.IntegerField(max_length=11, unique=True)
    vmail = models.CharField(max_length=100)
    vstate = models.CharField(max_length=100, null=True, blank=True)
    vstreet = models.CharField(max_length=170, null=True, blank=True)
    vcity = models.CharField(max_length=130, null=True, blank=True)
    vzip = models.CharField(max_length=100, null=True, blank=True)

    def __unicode__(self):
        return '%s %s %s' %(self.vname, str(self.vnumber), str(self.vmail))

class StoredDocs(models.Model):
    dnum = models.CharField(max_length=50)
    file_upload = models.FileField(upload_to='img', blank=True)

    def __unicode__(self):
        return '%s, %s' %(self.dnum, self.file_upload)

class Engine(models.Model):
    MARKET_OPT = (
        ('FI', 'Finland'),
        ('DK', 'Denmark'),
        ('SE', 'Sweden'),
        ('NO', 'Norway'),
        ('AT', 'Austria'),
        ('FR', 'France'),
        ('DE', 'Germany'),
        ('IT', 'Italy'),
        ('NL', 'Netherland'),
        ('PT', 'Portugal'),
        ('PL', 'Poland'),
        ('GB', 'Great Britain'),
        ('CH', 'Switzerland'),
        ('BE', 'Belgium'),
        ('ES', 'Spain')
        )

    CCODE_OPT = (
        ('0W', '0W'),
        ('0X', '0X'),
        ('0Y', '0Y'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
        ('14', '14'),
        ('15', '15'),
        ('16', '16'),
        ('18', '18'),
        ('19', '19'),
        ('20', '21'),
        ('23', '23'),
        ('29', '29'),
        ('30', '30'),
        ('31', '31'),
        ('34', '34'),
        ('36', '36'),
        ('42', '42'),
        ('45', '45'),
        ('46', '46'),
        ('47', '47'),
        ('49', '49'),
        ('52', '52'),
        ('54', '54'),
        ('55', '55'),
        ('56', '56'),
        ('57', '57'),
        ('58', '58'),
        ('60', '60'),
        ('64', '64'),
        ('65', '65'),
        ('66', '66'),
        ('69', '69'),
        ('78', '78'),
        ('80', '80'),
        ('82', '82'),
        ('85', '85')
        )

    LEVEL_OPT = (
        ('1', '1st'),
        ('2', '2nd'),
        ('3', '3rd'),
        ('4', '4th'),
        ('5', 'to scan'),
        ('6', 'critical'),
        ('7', 'non critical'),
        )

    INVSTATUS_OPT = (
        ('RJ', 'Rejected'),
        ('PO', 'Posted'),
        ('PD', 'Paid on'),
        ('NP', 'Not posted yet'),
        ('BL', 'Blocked'),
        ('MB', 'Manual block'),
        ('PK', 'Parked'),
        ('NR', 'Not received'),
        ('CA', 'Cancelled'),
        ('RE', 'Reversed'),
        ('PB', 'Posted - debit balance'),
        ('BC', 'Balance confirmation'),
        ('CD', 'Cash discount'),
        ('OX', 'Other'),
        ('IN', 'Interest note'),
    )

    INVSTATUS_OPT_NL = (
        ('RJ', 'Afgewezen'),
        ('PO', 'Verwerkt'),
        ('PD', 'Betaald'),
        ('NP', 'Nog niet goedgekeurd'),
        ('BL', 'Geblokkeerd'),
        ('NR', 'Niet ontvangen'),
        ('RE', 'Teruggeboekt'),
        ('PB', 'Verwerkt - negatief saldo'),
        ('OX', 'Overige redden')
    )

    INVSTATUS_OPT_FR = (
        ('RJ', 'Refusé'),
        ('PO', 'Comptabilisé'),
        ('PD', 'Payé'),
        ('NP', 'En cours de traitement'),
        ('BL', 'Anomalie sur la commande'),
        ('NR', 'Non reçu'),
        ('RE', 'En cours de traitement'),
        ('PB', 'comptabilisé - compte créditeur'),
        ('OX', 'Autres')
    )

    INVSTATUS_OPT_DE = (
        ('RJ', 'Abgelehnt'),
        ('PO', 'Verbucht'),
        ('PD', 'Bezahlt am'),
        ('NP', 'Noch nicht gebucht'),
        ('BL', 'Gesperrt'),
        ('PK', 'Vorerfasst'),
        ('NR', 'Nicht erhalten'),
        ('CA', 'Storniert'),
        ('PB', 'Verbucht - im sollsaldo'),
        ('CD', 'Skonto'),
        ('OX', 'Andere')
    )

    INVSTATUS_OPT_SE = (
        ('RJ', 'Avvisat'),
        ('PO', 'Bokfört'),
        ('PD', 'Betalt den'),
        ('NP', 'Inte bokfört än'),
        ('BL', 'Blockerat'),
        ('NR', 'Inte mottagits'),
        ('CA', 'Raderad'),
        ('RE', 'Annulerat'),
        ('PB', 'Bokfört - debit balans'),
        ('OX', 'Annat')
    )

    INVSTATUS_OPT_FI = (
        ('RJ', 'Hylätty'),
        ('PO', 'Kirjattu'),
        ('PD', 'Maksettu'),
        ('NP', 'Kirjaamatta'),
        ('BL', 'Pysäytetty'),
        ('NR', 'Ei saapunut'),
        ('CA', 'Peruutettu'),
        ('RE', 'Kumottu'),
        ('PB', 'Kirjattu - velkasaldo'),
        ('OX', 'Muu')
    )

    INVSTATUS_OPT_IT = (
        ('RJ', 'Rifiutato'),
        ('PO', 'Registrato'),
        ('PD', 'Pagato'),
        ('NP', 'Non ancora registrato'),
        ('BL', 'Bloccato'),
        ('NR', 'Non pervenuto'),
        ('PB', 'Registrato - saldo debitore'),
        ('OX', 'Altro')
    )

    INVSTATUS_OPT_PT = (
        ('RJ', 'Rejetada'),
        ('PO', 'Lançada na conta'),
        ('PD', 'Paga no dia '),
        ('NP', 'Ainda não está lançada'),
        ('PK', 'Está a esperar para aprovação'),
        ('BL', 'Bloqueada'),
        ('NR', 'Não recebida'),
        ('CA', 'Lançada e posteriormente anulada'),
    )

    BLOCK_TYPE = (
        ('TCM', 'Tax residence certificate missing'),
        ('CRX', 'Compensation with receivables'),
        ('CCN', 'Compensation with credit note'),
        ('DBR', 'Due to buyer request'),
        ('PTF', 'Will be paid to factor'),
        ('WBA', 'Wrong bank account'),
    )

    REJ_REASONS = (
        ("MPO", "Missing Purchase Order Number"),
        ("BIX", "Bad information"),
        ("DIX", "Duplicate invoice"),
        ("OTH", "Other"),
        ("IDX", "Invalid document"),
        ("WFI", "Wrong system - Route to FI box"),
        ("WSO", "Wrong system - Route to SOS box"),
        ("WCO", "Wrong system - Route to COM box"),
        ("IPO", "Invalid Purchase Order"),
        ("WCN", "Wrong company name"),
        ("WCA", "Wrong company address"),
        ("ICX", "Incorrect currency"),
        ("MCX", "Missing currency"),
        ("WVA", "Wrong VAT amount"),
        ("MVN", "Missing VAT number"),
        ("VMX", "Value on the invoice miscalculated"),
        ("DNV", "Data on the invoice not visible"),
        ("IDM", "Invoice date missing"),
        ("INM", "Invoice number missing"),
        ("MPX", "Missing pages"),
        ("TFM", "Tax free invoice-note missing"),
        ("DEM", "Delivery date / Delivery Note Missing"),
        ("QMX", "Quantity missing"),
        ("SDM", "Service description missing"),
        ("MIA", "Missing Invoice Amount"),
        ("IIX", "Incomplete Invoice"),
        ("MAI", "Missing Accounting Information"),
        ("IAI", "Invalid Accounting Information"),
        ("MAX", "Missing Approval"),
        ("IRA", "Invalid Remit To Address"),
        ("MRA", "Missing Remit To Address"),
        ("RNL", "Remit to address not linked to vendor's record"),
        ("VMX", "Vendor Master"),
        ("MUI", "Multiple invoices"),
        ("RES", "Rescan, poor quality"),
        ("BCV", "Vendor account not found in SAP"),
        ("BCS", "Statement attached"),
        ("BCI", "No invoice posted on vendor's account"),
    )

    REJ_REASONS_IT = (
        ("MPO", "Numero d'ordine mancante"),
        ("BIX", "Informazione errata"),
        ("DIX", "Fattura duplicato"),
        ("OTH", "Altro"),
        ("IDX", "Documento non valido"),
        ("WFI", "Sistema errato, girare su FI"),
        ("WSO", "Sistema errato, girare su SOS"),
        ("WCO", "Sistema errato, girare su COM"),
        ("IPO", "Numero d'ordine errato"),
        ("WCN", "Nome dell'azienda errato"),
        ("WCA", "Indirizzo dell'azienda errato"),
        ("ICX", "Valuta errata"),
        ("MCX", "Valuta mancante"),
        ("WVA", "Importo iva errato"),
        ("MVN", "Importo iva mancante"),
        ("VMX", "Importo della fattura erroneamente calcolato"),
        ("DNV", "Dati del documento non visibili"),
        ("IDM", "Data documento mancante"),
        ("INM", "Numero documento mancante"),
        ("MPX", "Pagine mancanti"),
        ("TFM", "Fattura esente da tasse - nota mancante"),
        ("DEM", "Data/Nota di consegna errate"),
        ("QMX", "Quantità mancante"),
        ("SDM", "Descrizione servizio mancante"),
        ("MIA", "Importo della fattura mancante"),
        ("IIX", "Documento incompleto"),
        ("MAI", "Dati contabili mancanti"),
        ("IAI", "Dati contabili errati"),
        ("MAX", "Autorizzazione mancante"),
        ("IRA", "Indirizzo spedizione errato"),
        ("MRA", "Indirizzo di spedizione mancante"),
        ("RNL", "Indirizzo di spedizione non corrisponde ai dati del fornitore"),
        ("VMX", "Dati fornitore"),
        ("MUI", "Fatture multiple"),
        ("RES", "Da reinserire - pessima qualità")
    )

    REJ_REASONS_PT = (
        ("MPO", "Recursar e devolver ao fornecedor - Falta n pedido"),
        ("BIX", "Recursar e devolver ao fornecedor - Informações incorrectas"),
        ("DIX", "Recursar - Factura dupla"),
        ("OTH", "Outros"),
        ("IDX", "Documento inválido"),
        ("IPO", "Pedido inválido"),
        ("WCN", "Nome da empresa errado"),
        ("WCA", "Endereço da empresa errado"),
        ("ICX", "Moeda incorrecta "),
        ("MCX", "Moeda inexistente "),
        ("WVA", "Montante IVA errado "),
        ("MVN", "Número  IVA inexistente"),
        ("VMX", "Valor na fatura calculado errado"),
        ("DNV", "Dados na fatura não visíveis"),
        ("IDM", "Data fatura inexistente"),
        ("INM", " Número  fatura inexistente"),
        ("MPX", "Páginas inexistentes"),
        ("TFM", "Nota fatura sem imposto inexistente"),
        ("DEM", "Data remessa / Nota remessa inexistente"),
        ("QMX", "Quantidade en falta"),
        ("SDM", "Descrição do serviço inexistente"),
        ("MIA", "Montante fatura inexistente"),

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.css" />
    <link href="{{ STATIC_URL }}css/stylesheet.css" type="text/css" rel="stylesheet" />
    <link type="text/css" href="{{ STATIC_URL }}jquery/css/ui-darkness/jquery-ui-1.10.3.custom.css" rel="stylesheet" />
    <link href="{{ STATIC_URL }}css/nav.css" type="text/css" rel="stylesheet" />
    {% block header %}
    {% endblock header %}
  </head>
  <body class="HPfont">
    {% block nav %}{% endblock nav %}
    {% block tablerep %}{% endblock tablerep %}
    {% block editaccount %}{% endblock editaccount %}
    {% block trackingform %}{% endblock trackingform %}
    {% block login_form %}{% endblock login_form%}
    {% block draft %}{% endblock draft %}
    {% block letter %}{% endblock letter %}
    {% block mailbuttons %}{% endblock mailbuttons %}
    {% block vendormodal %}{% endblock vendormodal %}
    {% block modalforbuyer %}{% endblock modalforbuyer %}
    {% block modalforshub %}{% endblock modalforshub %}
    <script src="{{ STATIC_URL }}jquery/js/jquery-1.9.1.js"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
    {% block menubar %}{% endblock menubar %}
    {% block content %}{% endblock %}
    {% block extra_content %}{% endblock extra_content %}
    {% block edittable %}{% endblock edittable %}
    {% block tablerepJS %}{% endblock tablerepJS %}
    {% block trackingjs %}{% endblock trackingjs %}
    {% block rcalendarJS %}{% endblock rcalendarJS %}
    {% block changepassJS %}{% endblock changepassJS %}
    {% block mailJS %}{% endblock mailJS %}
    {% block additionalJS %}{% endblock additionalJS %}

    <!--
    <script src="{{ STATIC_URL }}js/jquery-migrate-1.2.1.js"></script>
    <script src="{{ STATIC_URL }}jquery/json2.js"></script>
    !-->

    <script type="text/javascript" src="{{ STATIC_URL }}jquery/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery/js/csrf_protection.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/validation.js"></script>
    {% block additional_javascript %}
    {% endblock additional_javascript %}
  </body>
</html>

templates/calendar.html
{% extends "nav.html" %}
{% block content %}
<div id="prev-back">
  <button type="button" class="btn btn-primary btn-large prev">
    <span class="glyphicon glyphicon-arrow-left"></span>  Prev week
  </button>
  <button type="button" class="btn btn-primary btn-large next">
    Next week  <span class="glyphicon glyphicon-arrow-right"></span>
  </button>
</div>
<table class="table table-striped table-bordered">
  {% for header in headers %}
  {% if not forloop.first %}
  <th>{{ header }}</th>
  {% else %}
  <th>Date</th>
  {% endif %}
  {% endfor %}
  {% for row in tableresults %}
  <tr>
    {% for value in row %}
    {% if forloop.first %}
    <td>{{ value|date:"d-m-Y" }}</td>
    {% else %}
    <td class="{{ row.0|date:'Y-m-d' }}">{{ value }}</td>
    {% endif %}
    {% endfor %}
  </tr>
  {% endfor %}
</table>
{% endblock content %}
{% block rcalendarJS %}
<script src="{{ STATIC_URL}}jquery/rcalendar.js"></script>
{% endblock rcalendarJS %}

templates/forgot_password.html
{% extends "base.html" %}

{% block title %}Forgot Password{% endblock title %}

{% block content %}
<form method="post" action="{% url django.contrib.auth.views.password_reset %}">
    {% csrf_token %}
    <p>Please enter your email address. You will receive a link to create a new password via email.</p>
    <input type="email" name="email" placeholder="Your e-mail"><br/>
    <button type="submit">Send new password</button>
</form>
{% endblock content %}



templates/index.html
{% extends "navless.html" %}
{% block title %}
Login - Dunning Cruncher
{% endblock title %}
{% block centre_piece %}
<div id="wrapper">
  <form id="login" method="POST" action="/login/">
  <img id="hp-logo" src="{{ STATIC_URL }}images/logo.png" />
  {% csrf_token %}
  <table id="login-table">
    <tr>
      <th><label for="login-user">Username:</label></th>
      <td colspan="2">
	{{ login.uname }}
      </td>
    </tr>
    <tr>
      <th><label for="login-password">Password:</label></th>
      <td colspan="2">
	{{ login.passw }}
      </td>
    </tr>
    <tr>
      <td colspan="2">
	<a href="{% url 'password_reset' %}">Forgot your password?</a>
      </td>
      <td align="right">
	<input type="submit" id="add_button" value="Login"/>
      </td>
    </tr>
  </table>
  </form>
  <br><br><br><br><br><br>
  <div align="center"><small>WebApp powered by:</small></div>
  <div align="center"><small>django MariaDB NGINX Gunicorn</small></div>
</div>
{% endblock centre_piece %}

templates/nav.html
{% extends "base.html" %}
{% block title %}Dunning Cruncher{% endblock title %}
{% block nav %}
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'core.views.index' %}">Dunning Cruncher</a>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'core.views.index' %}">Home</a></li>
      {% if user.groups.values.0.name == 'SV' or user.groups.values.0.name == 'REP' %}
      <li><a href="{% url 'core.views.reporting' year month%}">Reporting</a></li>
      {% endif %}
      {% if user.groups.values.0.name == 'TL' %}
      <li><a href="{% url 'core.views.edit' %}">Review</a></li>
      <li><a href="{% url 'core.views.reporting' year month %}">Reporting</a></li>
      <li><a href="{% url 'core.views.tracking_calendar' year week %}">Reminders</a></li>
      {% endif %}
      {% if user.groups.values.0.name == 'RU' %}
      <li><a href="{% url 'core.views.edit' %}">Review</a></li>
       <li><a href="{% url 'core.views.tracking_calendar' year week %}"> Reminders</a></li>
      {% endif %}
      <li><a href="{% url 'django.contrib.auth.views.password_change' %}">Account</a></li>
    </ul>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <p class="navbar-text">Signed in as {{ welcome_name }}</p>
    <li><a href="{% url 'core.views.logout_view' %}">Logout</a></li>
  </ul>
</div>
{% if request.path == "/main/" %}
<div class="jumbotron">
  <div class="container">
    <h2>Hello, {{ user.first_name }}</h2>
    <p id="ptrack">To start tracking a new DL click on the below button.</p>
    <img class="logo" src="{{ STATIC_URL }}images/logo2.png">
    <button type="button" class="btn btn-primary" id="trbutton">
      <span class="glyphicon glyphicon-briefcase"></span> Track!
    </button>
  </div>
</div>
{% else %}
{% endif %}
{% endblock nav %}
{% block content %}{% endblock content %}
{% block tablerep %}{% endblock tablerep %}
{% block draft %}{% endblock draft %}
{% block letter %}{% endblock letter %}
{% block additionalJS %}{% endblock additionalJS %}
{% block mailbuttons %}{% endblock mailbuttons %}
{% block vendormodal %}{% endblock vendormodal %}
{% block modalforbuyer %}{% endblock modalforbuyer %}
{% block modalforshub %}{% endblock modalforshub %}
{% block mailJS %}{% endblock mailJS %}
{% block rcalendarJS %}{% endblock rcalendarJS %}
{% block tablerepJS %}{% endblock tablerepJS %}
{% block trackingform %}{% endblock trackingform %}
{% block editaccount %}{% endblock editaccount %}
{% block trackingjs %}
<script src="{{ STATIC_URL }}jquery/trackingjs.js">
</script>
{% endblock trackingjs %}
{% block changepassJS %}{% endblock changepassJS %}

templates/navless.html
{% extends "base.html" %}
{% block title %}
{% endblock title %}
{% block content %}
<!--[if IE]>
<link href="{{ STATIC_URL }}ie_styles.css" type="text/css" rel="stylesheet" />
<![endif]-->
<div id="centre-block">
{% block centre_piece %}
{% endblock centre_piece %}
</div>
{% endblock content %}

templates/password_change_done.html
{% extends "nav.html" %}
{% block title %}Success!{% endblock title %}
{% block content %}
<div id="changesuccess" class="alert alert-success col-lg-3"><b>Password changed successfully!</b></div>
{% endblock content %}

templates/tracking.html
{% extends "nav.html" %}
{% block trackingform %}
<form action="." class="form-horizontal" role="form" id="trform">
  {% csrf_token %}
  <fieldset class="fieldmain">
    <legend><b>DL tracking form</b></legend>
    <div class="form-group">
      <label class="col-lg-3 control-label">Clerk:</label>
      <div class="col-lg-2">
	<p class="form-control-static" id="vclerk" value="{{ user.get_full_name }}">{{ question.clerk }}</p> 
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-3 control-label">Market:</label>
      <div class="col-lg-2">
	<p class="form-control-static">{{ question.market }}</p>
      </div>
      <label class="col-lg-2 control-label">Company Code:</label>
      <div class="col-lg-1">
	<p class="form-control-static">{{ question.ccode }}</p>
      </div>
    </div>
    <div class ="form-group">
      <label class="col-lg-3 control-label">Received Date:</label>
      <div class="col-lg-2">
	<p class="form-control-static">{{ question.reminderdate }}</p>
      </div>
      <label class="col-lg-2 control-label">DL Level:</label>
      <div class="col-lg-1">
	<p class="form-control-static">{{ question.level }}</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-3 control-label">Action Date:</label>
      <div class="col-lg-2">
	<p class="form-control-static">{{ question.actiondate }}</p>
      </div>
      <label class="col-lg-2 control-label">DL Number:</label>
      <div class="col-lg-2">
	<p class="form-control-static">{{ question.remindernumber }}</p>
      </div>
    </div>
    <div class="addhiddendata">
      <div class="form-group">
	<label class="col-lg-3 control-label">Inv. number:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.invoicenumber }}</p>
	</div>
	<label class="col-lg-2 control-label">Inv. status:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.invoicestatus }}</p>
	</div>
	<div class="col-lg-2">
	  <button type="button" class="btn btn-primary btn-sm" id="addbutt">
	    Add  <span class="glyphicon glyphicon-plus"></span>
	  </button>
	  <button type="button" class="btn btn-primary btn-sm" id="rembutt">
	    Remove  <span class="glyphicon glyphicon-minus"></span>
	  </button>
	</div>
      </div>
      <div class="form-group addtohide rejpaidform">
	<label class="col-lg-3 control-label">Rejection reason:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.rejectreason }}</p>
	</div>
	<label class="col-lg-2 control-label">Others:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.reasonother }}</p>
	</div>
	<label class="col-lg-3 control-label">Paid on:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.paidon }}</p>
	</div>
	<label class="col-lg-3 control-label">Block type:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.blocktype }}</p>
	</div>
      </div>
      <div class="form-group">
	<label class="col-lg-3 control-label">Amount:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.amount }}</p>
	</div>
	<label class="col-lg-2 control-label">Currency:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.currency }}</p>
	</div>
      </div>
      <div class="form-group beforevendor">
	<label class="col-lg-3 control-label">Inv. Date:</label>
	<div class="col-lg-2">
	  <p class="form-control-static">{{ question.invoicedate }}</p>
	</div>
      </div>
    </div>
    <div class="form-group" id="vendorform">
      <label class="col-lg-3 control-label">Vendor number:</label>
      <div class="col-lg-2">
	<p class="form-control-static">{{ question.vendor }}</p>
      </div>
      <label class="col-lg-2 control-label">Vendor mail:</label>
      <div class="col-lg-3">
	<p class="form-control-static">
	  <div class="input-group">
	    <span class="input-group-addon">@</span>
	    {{ question.mailvendor }}
	  </div>
	</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-5 control-label">Actions:</label>
      <div class="col-lg-5 actioncheck">
	<label class="checkbox-inline">
	  <input type="checkbox" id="cfax" value="fax"> Fax
	</label>
	<label class="checkbox-inline">
	  <input type="checkbox" id="clist" value="list"> List
	</label>
	<label class="checkbox-inline">
	  <input type="checkbox" id="cmail" value="e-mail"> E-mail
	</label>
	<label class="checkbox-inline">
	  <input type="checkbox" id="cphone" value="phone"> Phone
	</label>
	<label class="checkbox-inline">
	  <input type="checkbox" id="cweb" value="website"> Website
	</label>
	<label class="checkbox-inline">
	  <input type="checkbox" id="noact" value="no action"> No action
	</label>
      </div>
    </div>
    </br>
    <div class="form-group">
      <label class="col-lg-5 control-label" for="id_file_upload">File input:</label>
      {{ fileform.file_upload }}
    </div>
    <div id="erralert" class="alert alert-danger col-lg-3"><b>Please check fields marked in red</b></div>
    </br>
    <div>
      <input type="button" value="Submit" id ="trackbutton" class="btn btn-primary btn-large">
    </div>
  </fieldset>
</form>
<div id="succmodal" class="modal fade">
  <div id="succalert" class="alert alert-success col-lg-3"><b>Item tracked successfully!</b></div>
</div>
{% endblock trackingform %}